# you can delete this line if you're not using Docker
image: docker:18.09

stages:
  - build

build1:
  stage: build
  script:
    - docker build --no-cache https://github.com/OpenSILEX/opensilex-opencpu-docker.git -t opensilex/opencpu
    - docker run -d -t -p 8004:8004 --name=opensilex-ocpu opensilex/opencpu:latest
      
